language: node_js
node_js:
  - lts/*

before_deploy: npm run predeploy

deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
